services:
  - type: web
    name: multi-factor-auth-system
    env: php
    plan: starter
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: DB_HOST
        value: ""
      - key: DB_DATABASE
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: ""
      - key: SMTP_SECURE
        value: ""
      - key: SMTP_AUTH_ENABLED
        value: ""
      - key: MAIL_FROM_ADDRESS
        value: ""
      - key: MAIL_FROM_NAME
        value: ""
      - key: SMTP_USERNAME
        value: ""
      - key: SMTP_PASSWORD
        value: ""
      - key: MAIL_DEBUG
        value: ""

databases:
  - name: mfa-auth-db
    engine: mysql
    plan: starter
    databaseName: secure_auth
